-d C:\Users\Aymen\OneDrive\Desktop\FPGA_CODES\fpga_to_test\impl\gwsynthesis\CNC_ETCHING_MACHINE.vg
-p GW1NR-9C-QFN88-6
-pn GW1NR-LV9QN88C6/I5
-cst C:\Users\Aymen\OneDrive\Desktop\FPGA_CODES\fpga_to_test\src\CNC_ETCHING_MACHINE.cst
-cfg C:\Users\Aymen\OneDrive\Desktop\FPGA_CODES\fpga_to_test\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
